"""
tests/test_strategy_sets_composite.py

Phase 2 of the composite ("Group A x Group B") Strategy Set design:
strategy_sets/composite.py's resolution/composition layer, and its
wiring into the real strategy_sets.expansion.expand_strategy_set()
entry point.

Real objects throughout -- real StrategyDefinition/IntermarketDefinition
shapes, a real StrategySetRepository backed by tmp_path (never
data/strategy_sets/, which is live user data), and REAL contract RIC
generation via core.futures_calendar (pure calendar arithmetic, no I/O,
no LSEG/database), mirroring tests/test_strategy_sets_expansion.py's own
approach. Nothing here fakes the strategy model or re-implements
Module 9's rolling logic.

The worked example throughout is the design brief's own:

    Group A = "STIR Flys"  selected [SR3 Fly, SON Fly]
    Group B = "Other Flys" selected [SR3 Fly, CRA Fly]

    -> (SR3 Fly - SR3 Fly: structurally zero, dropped -- Phase 3)
       SR3 Fly - CRA Fly, SON Fly - SR3 Fly, SON Fly - CRA Fly

Phase 3 note: "SR3 Fly - SR3 Fly" is still GENERATED by the Cartesian
pairing (a strategy may legitimately be selected on both sides, and the
pair still consumes its slot in the unordered-pair dedup) but is then
dropped by strategy_sets.composite.is_structurally_zero() before it is
returned, because every leg cancels. The structural-zero rule has its
own focused coverage in tests/test_strategy_sets_composite_structural_
zero.py; the tests here assert the resulting combination lists.
"""

from __future__ import annotations

import json

import pytest

from core import config
from core.config import BarInterval

from strategy_engine.combinations import StrategyInstance
from strategy_engine.definitions import StrategyDefinition
from strategy_engine.intermarket_combinations import (
    IntermarketStrategyInstance,
    generate_intermarket_instances,
)
from strategy_engine.intermarket_definitions import IntermarketDefinition, LegSpec

from strategy_sets.composite import (
    COMBINATION_NAME_SEPARATOR,
    expand_combinations,
    CompositeResolutionError,
    SourceStrategy,
    cartesian_pairs,
    compose_definition,
    composite_labels_by_definition_id,
    definition_legs,
    pair_identity,
    resolve_composite_combinations,
    strategy_identity,
)
from strategy_sets.expansion import expand_strategy_set
from strategy_sets.model import (
    IntermarketStrategySetEntry,
    StrategyGroup,
    StrategyGroupPair,
    StrategySet,
    StrategySetEntry,
)
from strategy_sets.repository import StrategySetRepository
from strategy_sets.serialization import strategy_set_to_dict

_START, _END = "2026-01-01", "2027-12-31"


# ---------------------------------------------------------------------
# Fixtures -- real Strategy Sets saved through the real repository
# ---------------------------------------------------------------------

def _fly(market_key: str, interval=BarInterval.DAILY, price_field="Close") -> StrategyDefinition:
    return StrategyDefinition(
        market_key=market_key, offsets=(0, 1, 2), weights=(1.0, -2.0, 1.0),
        interval=interval, price_field=price_field,
    )


def _spread(market_key: str) -> StrategyDefinition:
    return StrategyDefinition(
        market_key=market_key, offsets=(0, 1), weights=(1.0, -1.0), interval=BarInterval.DAILY,
    )


def _basis_entry(name="SOFR vs CORRA") -> IntermarketStrategySetEntry:
    definition = IntermarketDefinition(
        legs=(
            LegSpec(market_key="SOFR", offset=0, weight=1.0),
            LegSpec(market_key="CORRA", offset=0, weight=-1.0),
        ),
        interval=BarInterval.DAILY,
    )
    return IntermarketStrategySetEntry(name=name, definition=definition)


@pytest.fixture
def repo(tmp_path) -> StrategySetRepository:
    repository = StrategySetRepository(base_dir=str(tmp_path / "strategy_sets"))
    repository.save(
        StrategySet(
            name="STIR Flys",
            entries=(
                StrategySetEntry(name="SR3 Fly", definition=_fly("SOFR")),
                StrategySetEntry(name="SON Fly", definition=_fly("SONIA")),
                StrategySetEntry(name="CORRA Fly", definition=_fly("CORRA")),
            ),
        )
    )
    repository.save(
        StrategySet(
            name="Other Flys",
            entries=(
                StrategySetEntry(name="SR3 Fly", definition=_fly("SOFR")),
                StrategySetEntry(name="CRA Fly", definition=_fly("CORRA")),
            ),
        )
    )
    return repository


def _composite(
    name="Combos",
    a_source="STIR Flys",
    a_selected=("SR3 Fly", "SON Fly"),
    b_source="Other Flys",
    b_selected=("SR3 Fly", "CRA Fly"),
    entries=(),
    intermarket_entries=(),
) -> StrategySet:
    group_b = (
        None if b_source is None
        else StrategyGroup(source_set_name=b_source, selected_entry_names=b_selected)
    )
    return StrategySet(
        name=name,
        entries=entries,
        intermarket_entries=intermarket_entries,
        groups=StrategyGroupPair(
            group_a=StrategyGroup(source_set_name=a_source, selected_entry_names=a_selected),
            group_b=group_b,
        ),
    )


def _names(combinations) -> list[str]:
    return [c.name for c in combinations]


# ---------------------------------------------------------------------
# A x B Cartesian product
# ---------------------------------------------------------------------

def test_group_a_times_group_b_produces_the_cartesian_product(repo):
    # Four pairs are formed; "SR3 Fly - SR3 Fly" is structurally zero
    # and dropped (Phase 3), leaving three.
    combinations = resolve_composite_combinations(_composite(), repo)
    assert _names(combinations) == [
        "SR3 Fly - CRA Fly",
        "SON Fly - SR3 Fly",
        "SON Fly - CRA Fly",
    ]


def test_group_a_selection_order_is_respected(repo):
    reversed_a = _composite(a_selected=("SON Fly", "SR3 Fly"))
    assert _names(resolve_composite_combinations(reversed_a, repo)) == [
        "SON Fly - SR3 Fly",
        "SON Fly - CRA Fly",
        # "SR3 Fly - SR3 Fly" dropped here (structurally zero)
        "SR3 Fly - CRA Fly",
    ]


def test_group_b_selection_order_is_respected(repo):
    reversed_b = _composite(b_selected=("CRA Fly", "SR3 Fly"))
    assert _names(resolve_composite_combinations(reversed_b, repo)) == [
        "SR3 Fly - CRA Fly",
        # "SR3 Fly - SR3 Fly" dropped here (structurally zero)
        "SON Fly - CRA Fly",
        "SON Fly - SR3 Fly",
    ]


def test_results_are_never_sorted_alphabetically(repo):
    combinations = resolve_composite_combinations(
        _composite(a_selected=("SON Fly",), b_selected=("SR3 Fly", "CRA Fly")), repo
    )
    assert _names(combinations) == ["SON Fly - SR3 Fly", "SON Fly - CRA Fly"]
    assert _names(combinations) != sorted(_names(combinations))


def test_single_selection_on_each_side_produces_one_combination(repo):
    combinations = resolve_composite_combinations(
        _composite(a_selected=("SON Fly",), b_selected=("CRA Fly",)), repo
    )
    assert _names(combinations) == ["SON Fly - CRA Fly"]


def test_empty_selection_on_either_side_produces_nothing(repo):
    assert resolve_composite_combinations(_composite(a_selected=()), repo) == []
    assert resolve_composite_combinations(_composite(b_selected=()), repo) == []


def test_resolution_is_deterministic_across_repeated_calls(repo):
    composite = _composite()
    first = resolve_composite_combinations(composite, repo)
    second = resolve_composite_combinations(composite, repo)
    assert _names(first) == _names(second)
    assert [c.definition.legs for c in first] == [c.definition.legs for c in second]
    assert [c.definition.market_keys for c in first] == [c.definition.market_keys for c in second]


# ---------------------------------------------------------------------
# Same-strategy case / unordered duplicate rule
# ---------------------------------------------------------------------

def test_same_strategy_on_both_sides_is_allowed_at_the_pairing_layer(repo):
    # Selecting one strategy on BOTH sides is legitimate and is never
    # rejected as a selection error -- the pair is formed, composed, and
    # only then recognized as structurally zero and dropped (Phase 3).
    # compose_definition() itself is unchanged: it still produces the
    # full negated-B shape, which is what makes the cancellation exact.
    a = SourceStrategy("STIR Flys", "SR3 Fly", _fly("SOFR"))
    b = SourceStrategy("Other Flys", "SR3 Fly", _fly("SOFR"))
    assert compose_definition(a, b).weights == (1.0, -2.0, 1.0, -1.0, 2.0, -1.0)

    combinations = resolve_composite_combinations(
        _composite(a_selected=("SR3 Fly",), b_selected=("SR3 Fly",)), repo
    )
    assert combinations == []


def test_same_strategy_pair_is_generated_only_once(repo):
    # "SR3 Fly" appears in BOTH selections on each side -- the (SR3, SR3)
    # pair can be reached twice, is formed once, and is then dropped as
    # structurally zero. Using a spread on one side keeps a survivor so
    # this asserts the dedup, not just the drop.
    combinations = resolve_composite_combinations(
        _composite(
            a_source="STIR Flys", a_selected=("SR3 Fly",),
            b_source="Other Flys", b_selected=("SR3 Fly", "CRA Fly"),
        ),
        repo,
    )
    assert _names(combinations) == ["SR3 Fly - CRA Fly"]


def test_reverse_direction_duplicate_is_removed(repo):
    # A = [SR3, CRA], B = [CRA, SR3] -- the product contains both
    # (SR3, CRA) and (CRA, SR3), which are the SAME unordered pair.
    composite = _composite(
        a_source="Other Flys", a_selected=("SR3 Fly", "CRA Fly"),
        b_source="Other Flys", b_selected=("CRA Fly", "SR3 Fly"),
    )
    combinations = resolve_composite_combinations(composite, repo)
    # (SR3, SR3) and (CRA, CRA) are formed but structurally zero, so the
    # single cross pair is all that survives -- in its first-generated
    # orientation.
    assert _names(combinations) == ["SR3 Fly - CRA Fly"]
    # (CRA Fly, SR3 Fly) was dropped as the reverse of the first pair.
    assert "CRA Fly - SR3 Fly" not in _names(combinations)


def test_surviving_orientation_is_always_group_a_then_group_b(repo):
    composite = _composite(
        a_source="Other Flys", a_selected=("CRA Fly", "SR3 Fly"),
        b_source="Other Flys", b_selected=("SR3 Fly", "CRA Fly"),
    )
    combinations = resolve_composite_combinations(composite, repo)
    survivor = [c for c in combinations if {"SR3 Fly", "CRA Fly"} == {c.group_a.entry_name, c.group_b.entry_name}]
    assert len(survivor) == 1
    # Group A's own strategy is on the LEFT, even though the canonical
    # dedup key is order-insensitive.
    assert survivor[0].name == "CRA Fly - SR3 Fly"
    assert survivor[0].group_a.entry_name == "CRA Fly"
    assert survivor[0].group_b.entry_name == "SR3 Fly"
    # ... and leg order carries the same orientation: CORRA legs first.
    assert survivor[0].definition.market_keys[:3] == ("CORRA", "CORRA", "CORRA")


def test_pair_identity_is_order_insensitive(repo):
    a = SourceStrategy("STIR Flys", "SR3 Fly", _fly("SOFR"))
    b = SourceStrategy("Other Flys", "CRA Fly", _fly("CORRA"))
    assert pair_identity(a, b) == pair_identity(b, a)


def test_pair_identity_distinguishes_genuinely_different_pairs():
    a = SourceStrategy("S", "SR3 Fly", _fly("SOFR"))
    b = SourceStrategy("S", "CRA Fly", _fly("CORRA"))
    c = SourceStrategy("S", "SON Fly", _fly("SONIA"))
    assert pair_identity(a, b) != pair_identity(a, c)


# ---------------------------------------------------------------------
# Source-set identity: same name, different/identical shape
# ---------------------------------------------------------------------

def test_same_source_set_used_for_both_groups_works(repo):
    composite = _composite(
        a_source="STIR Flys", a_selected=("SR3 Fly", "SON Fly"),
        b_source="STIR Flys", b_selected=("SON Fly", "CORRA Fly"),
    )
    combinations = resolve_composite_combinations(composite, repo)
    # "SON Fly - SON Fly" cancels and is dropped (Phase 3).
    assert _names(combinations) == [
        "SR3 Fly - SON Fly",
        "SR3 Fly - CORRA Fly",
        "SON Fly - CORRA Fly",
    ]


def test_identically_named_strategies_with_different_shapes_do_not_collapse(repo):
    # "STIR Flys / SR3 Fly" is a SOFR fly; "Divergent / SR3 Fly" is a
    # SOFR *spread* -- same name, genuinely different strategy.
    repo.save(
        StrategySet(
            name="Divergent",
            entries=(StrategySetEntry(name="SR3 Fly", definition=_spread("SOFR")),),
        )
    )
    composite = _composite(
        a_source="STIR Flys", a_selected=("SR3 Fly",),
        b_source="Divergent", b_selected=("SR3 Fly",),
    )
    combinations = resolve_composite_combinations(composite, repo)
    assert len(combinations) == 1
    combination = combinations[0]
    assert combination.group_a.set_name == "STIR Flys"
    assert combination.group_b.set_name == "Divergent"
    # 3 fly legs + 2 negated spread legs -- not collapsed into one
    # self-cancelling strategy.
    assert len(combination.definition.legs) == 5
    assert combination.definition.weights == (1.0, -2.0, 1.0, -1.0, 1.0)


def test_identically_shaped_strategies_in_different_sets_are_the_same_strategy(repo):
    # "STIR Flys / SR3 Fly" and "Other Flys / SR3 Fly" are byte-identical
    # StrategyDefinitions. The surrounding architecture defines strategy
    # identity as the definition shape, never the label or the file it
    # lives in (see template_scanner.universe._candidate_identity and the
    # Excel import's own identity rule), so the reverse pair is a
    # duplicate.
    composite = _composite(
        a_source="STIR Flys", a_selected=("SR3 Fly", "SON Fly"),
        b_source="Other Flys", b_selected=("SR3 Fly",),
    )
    combinations = resolve_composite_combinations(composite, repo)
    # ("STIR Flys/SR3 Fly", "Other Flys/SR3 Fly") is the same shape on
    # both sides, so it cancels and is dropped (Phase 3).
    assert _names(combinations) == ["SON Fly - SR3 Fly"]
    assert strategy_identity(_fly("SOFR")) == strategy_identity(_fly("SOFR"))
    assert strategy_identity(_fly("SOFR")) != strategy_identity(_fly("SONIA"))


# ---------------------------------------------------------------------
# Composition -- reusing Module 9's model, no nesting
# ---------------------------------------------------------------------

def test_composed_definition_is_a_plain_intermarket_definition(repo):
    combination = resolve_composite_combinations(
        _composite(a_selected=("SR3 Fly",), b_selected=("CRA Fly",)), repo
    )[0]
    definition = combination.definition
    assert isinstance(definition, IntermarketDefinition)
    assert all(isinstance(leg, LegSpec) for leg in definition.legs)
    assert definition.market_keys == ("SOFR", "SOFR", "SOFR", "CORRA", "CORRA", "CORRA")
    assert definition.weights == (1.0, -2.0, 1.0, -1.0, 2.0, -1.0)
    assert [leg.offset for leg in definition.legs] == [0, 1, 2, 0, 1, 2]


def test_group_b_legs_are_negated_so_a_minus_a_is_structurally_zero(repo):
    # Composition is unchanged by Phase 3 -- checked directly, since the
    # resulting combination is (correctly) no longer returned.
    definition = compose_definition(
        SourceStrategy("STIR Flys", "SR3 Fly", _fly("SOFR")),
        SourceStrategy("Other Flys", "SR3 Fly", _fly("SOFR")),
    )
    by_offset: dict[int, float] = {}
    for leg in definition.legs:
        by_offset[leg.offset] = by_offset.get(leg.offset, 0.0) + leg.weight
    assert set(by_offset.values()) == {0.0}


def test_an_existing_intermarket_entry_can_be_a_group_member_without_nesting(repo):
    repo.save(
        StrategySet(name="Basis", entries=(), intermarket_entries=(_basis_entry(),))
    )
    composite = _composite(
        a_source="Basis", a_selected=("SOFR vs CORRA",),
        b_source="STIR Flys", b_selected=("SON Fly",),
    )
    combination = resolve_composite_combinations(composite, repo)[0]
    assert combination.name == "SOFR vs CORRA - SON Fly"
    definition = combination.definition
    # ONE flat IntermarketDefinition -- no nested definition anywhere.
    assert isinstance(definition, IntermarketDefinition)
    assert all(isinstance(leg, LegSpec) for leg in definition.legs)
    assert definition.market_keys == ("SOFR", "CORRA", "SONIA", "SONIA", "SONIA")
    assert definition.weights == (1.0, -1.0, -1.0, 2.0, -1.0)


def test_definition_legs_flattens_both_definition_shapes():
    single = definition_legs(_fly("SOFR"))
    assert single == (
        LegSpec("SOFR", 0, 1.0), LegSpec("SOFR", 1, -2.0), LegSpec("SOFR", 2, 1.0),
    )
    entry = _basis_entry()
    assert definition_legs(entry.definition) == entry.definition.legs


def test_same_market_composite_resolves_bp_per_point(repo):
    # A SOFR fly minus a SOFR spread: every leg is SOFR, so the bp
    # convention is unambiguous -- and enough exposure remains that it
    # is not structurally zero.
    repo.save(
        StrategySet(
            name="Spreads",
            entries=(StrategySetEntry(name="SR3 Spread", definition=_spread("SOFR")),),
        )
    )
    combination = resolve_composite_combinations(
        _composite(
            a_source="STIR Flys", a_selected=("SR3 Fly",),
            b_source="Spreads", b_selected=("SR3 Spread",),
        ),
        repo,
    )[0]
    assert combination.definition.market_keys == ("SOFR",) * 5
    assert combination.definition.bp_per_point == config.get_market("SOFR").bp_per_point


def test_cross_market_composite_leaves_bp_per_point_unset(repo):
    combination = resolve_composite_combinations(
        _composite(a_selected=("SR3 Fly",), b_selected=("CRA Fly",)), repo
    )[0]
    assert combination.definition.bp_per_point is None


def test_mismatched_interval_is_rejected_clearly(repo):
    repo.save(
        StrategySet(
            name="Hourly",
            entries=(
                StrategySetEntry(
                    name="SR3 Fly H", definition=_fly("SOFR", interval=BarInterval.HOURLY)
                ),
            ),
        )
    )
    composite = _composite(
        a_source="STIR Flys", a_selected=("SR3 Fly",),
        b_source="Hourly", b_selected=("SR3 Fly H",),
    )
    with pytest.raises(CompositeResolutionError, match="one interval"):
        resolve_composite_combinations(composite, repo)


def test_mismatched_price_field_is_rejected_clearly(repo):
    repo.save(
        StrategySet(
            name="HighField",
            entries=(
                StrategySetEntry(
                    name="SR3 Fly High", definition=_fly("SOFR", price_field="High")
                ),
            ),
        )
    )
    composite = _composite(
        a_source="STIR Flys", a_selected=("SR3 Fly",),
        b_source="HighField", b_selected=("SR3 Fly High",),
    )
    with pytest.raises(CompositeResolutionError, match="one price field"):
        resolve_composite_combinations(composite, repo)


# ---------------------------------------------------------------------
# Dangling references / nested composites
# ---------------------------------------------------------------------

def test_missing_source_strategy_set_is_a_clear_error(repo):
    composite = _composite(name="Combos", b_source="No Such Set")
    with pytest.raises(CompositeResolutionError) as exc:
        resolve_composite_combinations(composite, repo)
    message = str(exc.value)
    assert "Combos" in message           # the composite Strategy Set
    assert "Group B" in message          # which group
    assert "No Such Set" in message      # the source Strategy Set


def test_missing_selected_strategy_is_a_clear_error_not_a_silent_skip(repo):
    composite = _composite(a_selected=("SR3 Fly", "Deleted Fly"))
    with pytest.raises(CompositeResolutionError) as exc:
        resolve_composite_combinations(composite, repo)
    message = str(exc.value)
    assert "Combos" in message
    assert "Group A" in message
    assert "STIR Flys" in message
    assert "Deleted Fly" in message


def test_missing_selected_strategy_never_substitutes_another(repo):
    composite = _composite(b_selected=("Not There",))
    with pytest.raises(CompositeResolutionError):
        resolve_composite_combinations(composite, repo)


def test_nested_composite_source_set_is_rejected(repo):
    repo.save(_composite(name="Inner Composite"))
    composite = _composite(name="Outer", a_source="Inner Composite", a_selected=("SR3 Fly",))
    with pytest.raises(CompositeResolutionError, match="[Nn]ested composite"):
        resolve_composite_combinations(composite, repo)


def test_nested_composite_error_names_the_group_and_source(repo):
    repo.save(_composite(name="Inner Composite"))
    composite = _composite(name="Outer", b_source="Inner Composite", b_selected=("SR3 Fly",))
    with pytest.raises(CompositeResolutionError) as exc:
        resolve_composite_combinations(composite, repo)
    message = str(exc.value)
    assert "Outer" in message
    assert "Group B" in message
    assert "Inner Composite" in message


def test_composite_resolution_error_is_a_value_error(repo):
    with pytest.raises(ValueError):
        resolve_composite_combinations(_composite(a_source="Gone"), repo)


# ---------------------------------------------------------------------
# Group B optional / groups=None -- Phase 1 semantics preserved
# ---------------------------------------------------------------------

def test_groups_none_produces_no_combinations(repo):
    ordinary = StrategySet(
        name="Plain", entries=(StrategySetEntry(name="SR3 Fly", definition=_fly("SOFR")),)
    )
    assert resolve_composite_combinations(ordinary, repo) == []


def test_group_a_only_is_not_a_composite_product(repo):
    group_a_only = StrategySet(
        name="Half",
        entries=(),
        groups=StrategyGroupPair(
            group_a=StrategyGroup(source_set_name="STIR Flys", selected_entry_names=("SR3 Fly",))
        ),
    )
    assert resolve_composite_combinations(group_a_only, repo) == []


def test_group_a_only_source_is_not_even_resolved(repo):
    # No Group B means no product, so a Group-A-only set with a dangling
    # source is not an error either -- nothing is resolved at all.
    dangling_a_only = StrategySet(
        name="Half",
        entries=(),
        groups=StrategyGroupPair(
            group_a=StrategyGroup(source_set_name="Gone", selected_entry_names=("X",))
        ),
    )
    assert resolve_composite_combinations(dangling_a_only, repo) == []


# ---------------------------------------------------------------------
# Nothing is persisted
# ---------------------------------------------------------------------

def test_no_cartesian_results_are_persisted_into_the_model_or_json(repo):
    composite = _composite()
    combinations = resolve_composite_combinations(composite, repo)
    assert len(combinations) == 3

    # The model still carries only the configuration.
    assert composite.entries == ()
    assert composite.intermarket_entries == ()
    assert composite.groups.group_a.selected_entry_names == ("SR3 Fly", "SON Fly")

    data = strategy_set_to_dict(composite)
    assert data["entries"] == []
    assert set(data["groups"]) == {"group_a", "group_b"}
    assert set(data["groups"]["group_a"]) == {"source_set_name", "selected_entry_names"}
    text = json.dumps(data)
    for name in ("SR3 Fly - CRA Fly", "SON Fly - CRA Fly"):
        assert name not in text


def test_saving_and_reloading_a_composite_regenerates_the_same_combinations(repo):
    composite = _composite()
    repo.save(composite)
    reloaded = repo.load("Combos")
    assert _names(resolve_composite_combinations(reloaded, repo)) == _names(
        resolve_composite_combinations(composite, repo)
    )


# ---------------------------------------------------------------------
# End-to-end through expand_strategy_set()
# ---------------------------------------------------------------------

def test_expand_strategy_set_rolls_composite_combinations(repo):
    composite = _composite()
    instances = expand_strategy_set(composite, _START, _END, repository=repo)

    assert instances
    assert all(isinstance(i, IntermarketStrategyInstance) for i in instances)
    # Every instance came from one of the four composed definitions --
    # rolled by Module 9's own generate_intermarket_instances(), not by
    # any second engine.
    combinations = resolve_composite_combinations(composite, repo)
    expected = [
        instance
        for combination in combinations
        for instance in generate_intermarket_instances(combination.definition, _START, _END)
    ]
    assert [i.rics for i in instances] == [i.rics for i in expected]


def test_expand_strategy_set_composite_is_deterministic(repo):
    composite = _composite()
    first = expand_strategy_set(composite, _START, _END, repository=repo)
    second = expand_strategy_set(composite, _START, _END, repository=repo)
    assert [i.rics for i in first] == [i.rics for i in second]


def test_expand_strategy_set_composite_labels_reach_every_rolled_instance(repo):
    composite = _composite()
    combinations = resolve_composite_combinations(composite, repo)
    labels = composite_labels_by_definition_id(combinations)
    assert sorted(labels.values()) == sorted(_names(combinations))

    # The definition object is shared by reference across every rolled
    # instance, which is what makes the id-keyed label lookup work.
    for combination in combinations:
        rolled = generate_intermarket_instances(combination.definition, _START, _END)
        assert rolled
        assert all(instance.definition is combination.definition for instance in rolled)


def test_expand_strategy_set_composite_combines_with_ordinary_entries(repo):
    composite = _composite(
        entries=(StrategySetEntry(name="Own Fly", definition=_fly("SOFR")),),
        intermarket_entries=(_basis_entry(),),
    )
    instances = expand_strategy_set(composite, _START, _END, repository=repo)

    single_market = [i for i in instances if isinstance(i, StrategyInstance)]
    intermarket = [i for i in instances if isinstance(i, IntermarketStrategyInstance)]
    assert single_market  # the set's own ordinary entry still expands
    assert intermarket

    # Single-market instances always come first (documented ordering).
    assert [isinstance(i, StrategyInstance) for i in instances] == (
        [True] * len(single_market) + [False] * len(intermarket)
    )


def test_expand_strategy_set_composite_without_a_repository_is_a_clear_error(repo):
    with pytest.raises(CompositeResolutionError, match="repository"):
        expand_strategy_set(_composite(), _START, _END)


def test_expand_strategy_set_propagates_a_dangling_reference(repo):
    with pytest.raises(CompositeResolutionError):
        expand_strategy_set(_composite(b_source="Gone"), _START, _END, repository=repo)


# ---------------------------------------------------------------------
# Existing behaviour is unchanged
# ---------------------------------------------------------------------

def test_ordinary_single_market_expansion_is_unchanged(repo):
    ordinary = StrategySet(
        name="Plain",
        entries=(
            StrategySetEntry(name="SR3 Fly", definition=_fly("SOFR")),
            StrategySetEntry(name="SON Spread", definition=_spread("SONIA")),
        ),
    )
    # No repository argument at all -- the non-composite path never
    # needs one, exactly as before Phase 2.
    without = expand_strategy_set(ordinary, _START, _END)
    with_repo = expand_strategy_set(ordinary, _START, _END, repository=repo)
    assert [i.rics for i in without] == [i.rics for i in with_repo]
    assert all(isinstance(i, StrategyInstance) for i in without)
    assert without


def test_existing_intermarket_entry_expansion_is_unchanged(repo):
    entry = _basis_entry()
    strategy_set = StrategySet(name="Basis", entries=(), intermarket_entries=(entry,))
    instances = expand_strategy_set(strategy_set, _START, _END)
    expected = generate_intermarket_instances(entry.definition, _START, _END)
    assert [i.rics for i in instances] == [i.rics for i in expected]
    assert all(i.definition is entry.definition for i in instances)


def test_group_a_only_set_expands_only_its_own_entries(repo):
    strategy_set = StrategySet(
        name="Half",
        entries=(StrategySetEntry(name="SR3 Fly", definition=_fly("SOFR")),),
        groups=StrategyGroupPair(
            group_a=StrategyGroup(source_set_name="STIR Flys", selected_entry_names=("SR3 Fly",))
        ),
    )
    instances = expand_strategy_set(strategy_set, _START, _END, repository=repo)
    plain = StrategySet(
        name="Half", entries=(StrategySetEntry(name="SR3 Fly", definition=_fly("SOFR")),)
    )
    assert [i.rics for i in instances] == [
        i.rics for i in expand_strategy_set(plain, _START, _END)
    ]


def test_combination_name_separator_is_the_documented_orientation(repo):
    combination = resolve_composite_combinations(
        _composite(a_selected=("SR3 Fly",), b_selected=("CRA Fly",)), repo
    )[0]
    assert combination.name == f"SR3 Fly{COMBINATION_NAME_SEPARATOR}CRA Fly"
    assert combination.name.split(COMBINATION_NAME_SEPARATOR) == ["SR3 Fly", "CRA Fly"]


# ---------------------------------------------------------------------
# Lower-level helpers
# ---------------------------------------------------------------------

def test_cartesian_pairs_preserves_order_and_dedupes():
    a = SourceStrategy("S", "A1", _fly("SOFR"))
    b = SourceStrategy("S", "B1", _fly("CORRA"))
    pairs = cartesian_pairs([a, b], [b, a])
    assert [(x.entry_name, y.entry_name) for x, y in pairs] == [
        ("A1", "B1"),   # kept; ("B1", "A1") below is its reverse
        ("A1", "A1"),
        ("B1", "B1"),
    ]


def test_compose_definition_keeps_group_a_legs_first():
    a = SourceStrategy("S", "A", _spread("SOFR"))
    b = SourceStrategy("S", "B", _spread("CORRA"))
    definition = compose_definition(a, b)
    assert definition.market_keys == ("SOFR", "SOFR", "CORRA", "CORRA")
    assert definition.weights == (1.0, -1.0, -1.0, 1.0)


def test_expand_combinations_rolls_the_same_definitions_it_was_given(repo):
    combinations = resolve_composite_combinations(_composite(), repo)
    instances = expand_combinations(combinations, _START, _END)
    assert instances
    definitions = {id(c.definition) for c in combinations}
    assert {id(i.definition) for i in instances} == definitions


def test_expand_combinations_matches_expand_strategy_set(repo):
    composite = _composite()
    combinations = resolve_composite_combinations(composite, repo)
    assert [i.rics for i in expand_combinations(combinations, _START, _END)] == [
        i.rics for i in expand_strategy_set(composite, _START, _END, repository=repo)
    ]


def test_labels_pair_with_the_resolution_they_came_from(repo):
    combinations = resolve_composite_combinations(_composite(), repo)
    labels = composite_labels_by_definition_id(combinations)
    instances = expand_combinations(combinations, _START, _END)
    assert all(labels[id(i.definition)] for i in instances)
    assert {labels[id(i.definition)] for i in instances} == set(_names(combinations))

    # Documented identity caveat: a SEPARATE resolution builds fresh
    # definition objects, so its label map does not apply to these
    # instances -- resolve once, then roll that same list.
    other_labels = composite_labels_by_definition_id(
        resolve_composite_combinations(_composite(), repo)
    )
    assert all(id(i.definition) not in other_labels for i in instances)
